---

- name: detect installed vaultwarden cli
  block:
    - name: detect if vaultwarden cli exists
      ansible.builtin.stat:
        path: "{{ vaultwarden_config.directories.data }}/rbw"
      register: vaultwarden_cli_version_directory

    - name: detect if vaultwarden cli exists
      ansible.builtin.stat:
        path: "{{ vaultwarden_config.directories.data }}/rbw_{{ vaultwarden_cli.version }}/rbw"
      register: vaultwarden_cli_version_file

    - name: define vaultwarden_cli_installed
      ansible.builtin.set_fact:
        vaultwarden_cli_installed: "{{ vaultwarden_cli_version_file.stat.exists }}"

- name: vaultwarden cli
  when:
    - vaultwarden_cli.state | default('absent') in ["absent", "present"]
    - vaultwarden_cli.state | default('absent') == "present"
    - vaultwarden_cli_version_directory.stat.isdir | default('false') or
      not vaultwarden_cli_installed
  block:
    - name: download vaultwarden cli
      become: true
      ansible.builtin.get_url:
        # https://github.com/doy/rbw/releases/download/1.10.1/rbw_1.10.1_linux_amd64.tar.gz
        url: "{{ vaultwarden_release.cli.download_url }}/download/{{ vaultwarden_cli.version }}/{{ vaultwarden_release.cli.file }}"
        dest: /tmp/
        mode: 0644
        validate_certs: false
      register: _download
      until: _download is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: create vaultwarden cli directory
      ansible.builtin.file:
        state: directory
        path: "{{ vaultwarden_config.directories.data }}/rbw_{{ vaultwarden_cli.version }}"
        owner: vaultwarden
        group: vaultwarden
        mode: 0775

    - name: install vaultwarden cli
      ansible.builtin.unarchive:
        src: "/tmp/{{ vaultwarden_release.cli.file }}"
        dest: "{{ vaultwarden_config.directories.data }}/rbw_{{ vaultwarden_cli.version }}/"
        remote_src: true
        owner: vaultwarden
        group: vaultwarden

    - name: create link for cli client
      ansible.builtin.file:
        src: "{{ vaultwarden_config.directories.data }}/rbw_{{ vaultwarden_cli.version }}/rbw"
        dest: "{{ vaultwarden_config.directories.data }}/rbw"
        state: link
        owner: vaultwarden
        group: vaultwarden
        force: true
        follow: false

    - name: create cli configuration directory
      ansible.builtin.file:
        state: directory
        path: "${HOME}/.config/rbw"
        mode: 0750

    - name: create cli configuration
      ansible.builtin.template:
        src: etc/rbw/config.json.j2
        dest: "${HOME}/.config/rbw/config.json"
        backup: true
        mode: 0644

    - name: create custom fact file
      bodsch.core.facts:
        name: vaultwarden_cli
        facts:
          version: "{{ vaultwarden_cli.version }}"

- name: remove vaultwarden cli
  when:
    - vaultwarden_cli.state | default('absent') == "absent"
    # - vaultwarden_cli_installed
  block:
    - name: remove link for cli client
      ansible.builtin.file:
        path: "{{ vaultwarden_config.directories.data }}/rbw"
        state: absent
        force: true

    - name: remove cli client
      ansible.builtin.file:
        path: "{{ vaultwarden_config.directories.data }}/rbw_{{ vaultwarden_cli.version }}"
        state: absent
        force: true

    - name: remove cli configuration
      ansible.builtin.file:
        state: absent
        path: "${HOME}/.config/rbw"

    - name: remove custom fact file
      ansible.builtin.file:
        state: absent
        path: "/etc/ansible/facts.d/vaultwarden_cli.fact"

...
