---

- name: detect installed vaultwarden
  block:
    - name: detect if vaultwarden exists
      ansible.builtin.stat:
        path: /usr/bin/vaultwarden
      register: vaultwarden_binary_file

    - name: define vaultwarden_installed
      ansible.builtin.set_fact:
        vaultwarden_installed: "{{ vaultwarden_binary_file.stat.exists }}"

# debian based
#
- name: debian based
  when:
    - ansible_os_family | lower == 'debian'
  block:
    - name: download vaultwarden GPG
      become: true
      ansible.builtin.get_url:
        url: https://bitwarden-deb.tech-network.de/bananian-keyring.gpg
        dest: /etc/apt/trusted.gpg.d/bananian-keyring.gpg
        mode: 0644
      register: _download_gpg
      until: _download_gpg is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: add vaultwarden repo sources
      ansible.builtin.template:
        src: etc/apt/vaultwarden.list.j2
        dest: /etc/apt/sources.list.d/vaultwarden.list
        mode: 0644

    - name: update package cache
      become: true
      ansible.builtin.package:
        update_cache: true

- name: create policy-rc.d
  when:
    - not vaultwarden_installed
    - ansible_os_family | lower == 'debian'
  ansible.builtin.copy:
    dest: /usr/sbin/policy-rc.d
    content: |
      #!/bin/sh
      exit 101
    mode: 0755
  tags:
    - vaultwarden
    - vaultwarden_install

- name: install package
  when:
    - not vaultwarden_installed
  ansible.builtin.package:
    name: "{{ vaultwarden_packages }}"
    state: present
  tags:
    - vaultwarden
    - vaultwarden_install

- name: create the systemd service file
  when:
    - ansible_service_mgr | lower == "systemd"
  ansible.builtin.template:
    src: init/systemd/vaultwarden.service.j2
    dest: "{{ systemd_lib_directory }}/vaultwarden.service"
    owner: root
    group: root
    mode: 0644
  notify:
    - daemon-reload
    - restart service

- name: remove policy-rc.d
  when:
    - not vaultwarden_installed
    - ansible_os_family | lower == 'debian'
  ansible.builtin.file:
    path: /usr/sbin/policy-rc.d
    state: absent
  tags:
    - vaultwarden
    - vaultwarden_install


- name: merge vaultwarden configuration between defaults and custom
  ansible.builtin.set_fact:
    vaultwarden_config: "{{ vaultwarden_defaults_config | combine(vaultwarden_config, recursive=True) }}"

- name: vaultwarden web
  when:
    - vaultwarden_config.web_vault.enabled | default('false') | bool
    - vaultwarden_config.directories.web_vault is defined
    - vaultwarden_config.directories.web_vault | string | length > 0
  block:

    - name: create logging directory
      ansible.builtin.file:
        state: directory
        path: "{{ vaultwarden_config.directories.web_vault }}"
        owner: vaultwarden
        group: vaultwarden
        mode: 0775

    - name: download vaultwarden web
      become: true
      ansible.builtin.get_url:
        url: "https://github.com/dani-garcia/bw_web_builds/releases/download/v{{ vaultwarden_webvault.version }}/bw_web_v{{ vaultwarden_webvault.version }}.tar.gz"
        dest: /tmp/
        mode: 0644
      register: _download
      until: _download is succeeded
      retries: 5
      delay: 2
      check_mode: false

    - name: download vaultwarden web
      ansible.builtin.unarchive:
       #      https://github.com/dani-garcia/bw_web_builds/releases/download/v2024.3.1/bw_web_v2024.3.1.tar.gz
       #      https://github.com/dani-garcia/bw_web_builds/releases/download/v2024.3.1/bw_web_v2024.3.1.tar.gz,
        src: "https://github.com/dani-garcia/bw_web_builds/releases/download/v{{ vaultwarden_webvault.version }}/bw_web_v{{ vaultwarden_webvault.version }}.tar.gz"
        dest: "{{ vaultwarden_config.directories.web_vault }}"
        remote_src: true
        owner: vaultwarden
        group: vaultwarden



...
