---

nginx_logformat:
  json_combined:
    format: |
      '{'
        '"time_local": "$time_local",'
        '"remote_addr": "$remote_addr",'
        '"remote_user": "$remote_user",'
        '"request": "$request",'
        '"status": "$status",'
        '"body_bytes_sent": "$body_bytes_sent",'
        '"request_time": "$request_time",'
        '"http_referrer": "$http_referer",'
        '"http_user_agent": "$http_user_agent"'
      '}';
    # escape: json

nginx_http:
  client:                                                 #
    max_body_size: "128M"

  maps:
    - name: http_upgrade
      description: connection_upgrade
      variable: connection_upgrade
      mapping:
        - source: "''"
          result: "''"
        - source: default
          result: upgrade

nginx_vhosts:
  - name: vault
    filename: 00-vault.conf
    state: present  # default: present
    enabled: true   # default: true

    domains:
      - vault.molecule.lan

    listen:
      - 443 ssl http2

    redirect:
      from_port: 80

    upstreams:
      - name: vaultwarden-default
        servers:
          - 127.0.0.1:8000

    logfiles:
      access:
        file: /var/log/nginx/vault.molecule.lan/access.log
        loglevel: main
      error:
        file: /var/log/nginx/vault.molecule.lan/error.log
        loglevel: notice

    ssl:
      enabled: true
      ciphers: default
      certificate: "{{ snakeoil_extract_to }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.pem"
      certificate_key: "{{ snakeoil_extract_to }}/{{ snakeoil_domain }}/{{ snakeoil_domain }}.key"
      dhparam: "{{ snakeoil_extract_to }}/{{ snakeoil_domain }}//dh.pem"

    locations:
      "/":
        options: |
          proxy_http_version 1.1;
          proxy_set_header Upgrade $http_upgrade;
          proxy_set_header Connection $connection_upgrade;

          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;

          proxy_pass http://vaultwarden-default;
