---

- name: daemon-reload
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
    force: true
  when:
    - ansible_service_mgr | lower == "systemd"

- name: restart service
  ansible.builtin.service:
    name: vaultwarden
    state: restarted

- name: reload service
  become: true
  ansible.builtin.service:
    name: vaultwarden
    state: reloaded

...
