---

mariadb_root_password: Y5FZfKXzCeOWGf4kBOiFSp6Il

mariadb_root_password_update: true

mariadb_databases:
  - name: "{{ database_schema }}"

mariadb_users:
  - name: "{{ database_user }}"
    host: "%"
    password: "{{ vault__database_password }}"
    priv: "{{ database_user }}.*:ALL"
    encrypted: false

mariadb_config_mysqld:
  bind-address: 0.0.0.0
  socket: "{{ mariadb_socket }}"
  skip-external-locking:
  skip-name-resolve: 1
  performance_schema: 1
  expire_logs_days: 2
  max_connections: 20

...
